# Generated by Django 3.2.23 on 2023-12-28 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumniinfo',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='alumni_photos/'),
        ),
    ]
