# Generated by Django 5.0 on 2023-12-29 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alumniinfo_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumniinfo',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/alumni_photos/'),
        ),
    ]
