# Generated by Django 5.0 on 2023-12-29 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_alumniinfo_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumniinfo',
            name='department',
            field=models.CharField(choices=[('engineering', 'Engineering'), ('other_department', 'Other Department')], default='engineering', max_length=255),
        ),
    ]
