# Generated by Django 5.0 on 2023-12-29 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alumniinfo_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumniinfo',
            name='department',
            field=models.CharField(choices=[('computer_engineering', 'Computer Engineering'), ('electrical_department', 'Electrical Department'), ('electronics_department', 'Electronics Department'), ('automobile_department', 'Automobile Department'), ('mechanical_department', 'Mechanical Department'), ('civil_department', 'Civil Department')], default='engineering', max_length=255),
        ),
    ]
