# Generated by Django 5.0 on 2023-12-29 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_alumniinfo_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumniinfo',
            name='department',
            field=models.CharField(choices=[('Computer Engineering', 'computer_engineering'), ('electrical_department', 'Electrical Department'), ('electronics_department', 'Electronics Department'), ('automobile_department', 'Automobile Department'), ('mechanical_department', 'Mechanical Department'), ('civil_department', 'Civil Department')], default='computer_engineering', max_length=255),
        ),
    ]
