# Generated by Django 5.0 on 2023-12-29 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_alumniinfo_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumniinfo',
            name='major',
        ),
    ]
