# Generated by Django 5.0 on 2023-12-29 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_alumniinfo_major'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumniinfo',
            name='industry',
            field=models.CharField(choices=[('it_software', 'IT/Software'), ('finance', 'Finance'), ('healthcare', 'Healthcare'), ('manufacturing', 'Manufacturing'), ('education', 'Education'), ('construction', 'Construction'), ('telecommunications', 'Telecommunications'), ('retail', 'Retail'), ('energy', 'Energy'), ('media', 'Media/Entertainment'), ('pharmaceutical', 'Pharmaceutical'), ('aerospace', 'Aerospace'), ('automotive', 'Automotive'), ('consulting', 'Consulting'), ('biotechnology', 'Biotechnology'), ('hospitality', 'Hospitality'), ('insurance', 'Insurance'), ('real_estate', 'Real Estate'), ('environmental', 'Environmental Services'), ('government', 'Government'), ('research', 'Research'), ('logistics', 'Logistics/Supply Chain'), ('sports', 'Sports'), ('non_profit', 'Non-profit'), ('other', 'Other'), ('fashion', 'Fashion'), ('marketing', 'Marketing/Advertising'), ('tech_startups', 'Tech Startups'), ('legal', 'Legal Services'), ('fitness', 'Fitness/Wellness'), ('pharmacy', 'Pharmacy'), ('art_design', 'Art/Design'), ('music', 'Music'), ('food_beverage', 'Food and Beverage'), ('tourism', 'Tourism/Travel'), ('e-commerce', 'E-commerce'), ('Other', 'Other')], default='Other', max_length=255),
        ),
    ]
